name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    # 运行所需要的虚拟机环境
    runs-on: ubuntu-latest
    steps:
      # 将代码拉取到虚拟机
      - name: Checkout
        uses: actions/checkout@v2

      # 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 安装依赖
      - name: Install Dependencies
        run: pnpm install

      # 打包
      - name: Build
        run: pnpm build

      # 部署
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.SSH_DIR }}
            git pull
            rm -rf /var/www/mcd/*
            cp -r ./dist/* /var/www/mcd
            nginx -s reload
